### ISSUE TITLE
YYYYMMDD as directory-name-format?

### ISSUE THREAD

**Issue by andreas-roehler** [neongreen/study-haskell#1]
Maybe change the format of the folder still, as it will sort easier?

Cheers,
Andreas

**Comment by neongreen** [comment]
Makes sense. (Though let's have YYYY-MM-DD.)

I just gave you commit access, feel free to push directly to the repo. Just don't forget to post an updated link in the meetup comments.

**Comment by andreas-roehler** [comment]
Great, thanks.
