### ISSUE TITLE
Question WRT type of Just

### ISSUE THREAD

**Issue by andreas-roehler** [neongreen/study-haskell#12]
Related question: it's possible to write

maybe 1 (*2) (Just 2)

but not 
maybe 1 (*2) 2

Hmm...

**Comment by andreas-roehler** [comment]
Return what the first form returns. Didn't see resp. understand what that wrapper (Just ...) is good for. Providing some barrier, preventing code injection?

**Comment by andreas-roehler** [comment]
Here an example from 
https://wiki.haskell.org/Maybe:

f::Int -> Maybe Int
f 0 = Nothing
f x = Just x
 
g :: Int -> Maybe Int
g 100 = Nothing
g x = Just x
 
h ::Int -> Maybe Int
h x = case f x of
         Just n -> g n
         Nothing -> Nothing
 
h' :: Int -> Maybe Int
h' x = do n <- f x
              g n
 -- Now

let a = h' 99
λ> a
Just 99
λ> let b = h' 2
λ> b
Just 2

 --- 

The Problem:  use of a function to select/verify an Int undergoes a kind of type-cast (?)

**Comment by neongreen** [comment]
> Didn't see resp. understand what that wrapper (Just ...) is good for. 

I can't say it's "good"; nullable types are also a valid design. However, introducing subtyping would add extra complexity to the type system.

**Comment by neongreen** [comment]
Reopen if it's still unclear after today.
