### ISSUE TITLE
Do we need "module Main"?

### ISSUE THREAD

**Issue by andreas-roehler** [neongreen/study-haskell#2]
AFAIU that naming/calling convention is a suboptimal thing and should only be mentioned WRT to legacy code. Wrong?

Cheers, 
Andreas

**Comment by neongreen** [comment]
Hm. What is the right convention nowadays?

**Comment by andreas-roehler** [comment]
It's about suitability. Also seeing a minor and a major issue. What about the following rule:
"Don't introduce arbitrary symbols which have meaning in a content
nearby."

Case this is accepted and the "Main" in "Main.hs" has no syntactic
role, it shouldn't be named like that.

The more interesting and original question is discussed here:

https://stackoverflow.com/questions/11112371/to-write-or-not-to-write-module-main-where-in-haskell

**Comment by neongreen** [comment]
I agree that the file shouldn't be named `Main.hs` (in our repo, anyway). Feel free to rename it to something more fitting (Transform is good) as long as you also rename other files for consistency.

I would not agree that an a priori theoretical consideration (in this case, "Don't introduce arbitrary symbols which have meaning in a content nearby") can be called _a convention_. Conventions are customs. If people commonly do something stupid, well, it's a stupid convention, but a convention nonetheless.

Finally, as a pedagogical principle, I would like to clearly separate the "is" and the "ought to". Everybody is welcome to argue about how things ought to be, sure, but I would like to avoid nudging people towards my or somebody else's "ought to" unless a clear _practical_ benefit can be demonstrated.

**Comment by andreas-roehler** [comment]
On 26.11.18 19:23, Artyom Kazak wrote:
> I agree that the file shouldn't be named |Main.hs| (in our repo, 
> anyway). Feel free to rename it to something more fitting (Transform is 
> good)

Done
  as long as you also rename other files for consistency.

Didn't see any dependency. Missed some?

> 
> I would not agree that an a priori theoretical consideration (in this 
> case, "Don't introduce arbitrary symbols which have meaning in a content 
> nearby") can be called /a convention/. Conventions are customs. If 
> people commonly do something stupid, well, it's a stupid convention, but 
> a convention nonetheless.
> 
> Finally, as a pedagogical principle, I would like to clearly separate 
> the "is" and the "ought to". Everybody is welcome to argue about how 
> things ought to be, sure, but I would like to avoid nudging people 
> towards my or somebody else's "ought to" unless a clear /practical/ 
> benefit can be demonstrated.
> 

Please understand all my thesis as question. It's about learning and I'm 
far from being sure in these things.

And thanks again BTW for your well done meetup. That combination of 
reading, reflection and example is excellent - at least for my taste.

Looking forward,
Andreas

**Comment by neongreen** [comment]
Well, if it was a question then the answer is "it doesn't matter"; `module Main (main) where` is equivalent to its absence so it's a matter of taste. (`module Main where`, without the export list, might be less optimized indeed, but I'm not sure it's still true for recent GHCs; and it also doesn't apply when your `main.hs` file is slim, which is often the case.)

Once you look at it as a "matter of taste" problem, there are at least three considerations I can think of:

1. Strive to have as little boilerplate as possible (in the absence of other tradeoffs). Boilerplate has a bunch of adverse effects which I will not bother listing here.

2. Try to be consistent; if other modules start with `module XYZ` then why not `Main` as well? Less questions from beginners, smaller chance that somebody's hastily written shell script will miss your module when grepping for `^module`, etc. Or, to pick a more realistic example, if somebody wants to document the main module with `-- |`, they wouldn't have to wonder whether Haddock will work on a module without a `module` header. (I actually don't know the answer off the top of my head!)

3. Try to follow conventions (again, going against conventions has adverse effects which I will not bother listing here). I'm actually not sure about that, but I think that more often than not I see main modules with a `module Main` header.

Which of those considerations should "win" is very much a matter of the circumstances you're in.

**Comment by andreas-roehler** [comment]
Agreed. Let's assume you start a company and it's time and space to reflect your preffered style. The idea is to call rather by a specific name and writing something like:

-- Types are inferred up and down
transaktion :: IO ()
transaktion = readLn >>= (print.(*(13::Int)).transform)

**Comment by neongreen** [comment]
(Or maybe it was intended to be left open? I'm not sure.)
